### ISSUE TITLE
MySQL JSON doesn't work

### ISSUE THREAD

**Issue by Antsypc** [javaplugs/mybatis-jackson#1]
MySQL 5.7+ has JSON type, I add your typehandler but it doesn't work, and there are errors.

> Error parsing Mapper XML. Cause: java.lang.IllegalStateException: No typehandler found for property friends

Is there anything wrong with my usage?

**Comment by rumatoest** [comment]
Hi. As you can see this JSON mapper can work with any string type, thus you must pass JSON to/from JDBC as String other cases are not supported.

BTW error you posted here is totally irrelevant, because  JSON type handler has nothing to do with XML.
